### ISSUE TITLE
Add All Victim Fields

### ISSUE THREAD

**Issue by utkonos** [ThreatConnect-Inc/ThreatConnect_Developer_Docs#113]
### Description:
The victim endpoint for creating a victim only lists "name" as a field in the example. The following fields are also valid:
description
org
suborg
workLocation
nationality

Example:
{"name":"asdfasdf222","description":"descriptionasdfasdfasdfasdf","org":"asdfasdf","suborg":"ddddd","workLocation":"ddfdfdfd","nationality":"deeeee"}

### Link(s):
-

**Comment by fhightower** [comment]
https://docs.threatconnect.com/en/latest/rest_api_docs.html#victims
