### ISSUE TITLE
Table 40 needs to be fixed

### ISSUE THREAD

**Issue by slabe-svetlo** [ThreatConnect-Inc/ThreatConnect_Developer_Docs#127]
### Description:
Odd spacing issues... probably during the mass of table updates. Right above the below...

### Link(s):
- 
https://docs.threatconnect.com/en/latest/rest_api_docs/?highlight=attributes#batch-indicator-input-file-format

**Comment by fhightower** [comment]
@slabe-svetlo : I have a process for fixing malformed tables easily. I can take care of this.
