### ISSUE TITLE
Fix code highlights table in Results Retrieve Filter Example

### ISSUE THREAD

**Issue by slabe-svetlo** [ThreatConnect-Inc/ThreatConnect_Developer_Docs#128]
### Link(s):
- 
https://docs.threatconnect.com/en/latest/python_sdk/?highlight=results.retrieve#filter-example

**Comment by fhightower** [comment]
@slabe-svetlo : I have a quick, easy way to fix tables, so I can take care of this. There will probably be a lot of tables that are poorly formatted from the transition over to restructured text.

**Comment by slabe-svetlo** [comment]
Ahh.. ok... same with the markdown to GitHub Markdown conversion...
