### ISSUE TITLE
Document Expected Filename Format for JS Apps

### ISSUE THREAD

**Issue by fhightower** [ThreatConnect-Inc/ThreatConnect_Developer_Docs#27]
(Original issue 25)

http://docs.threatconnect.com/#developing-a-javascript-app
Document that app .zip filenames need to have underscores in place of spaces.

- [ ] write prose
- [ ] review prose
- [ ] update docs

**Comment by slabe-svetlo** [comment]
You think adding the file name format to this section would be better?

http://docs.threatconnect.com/#deployment-configuration-file

**Comment by fhightower** [comment]
Yes, that makes a lot more sense. Good catch!

**Comment by fhightower** [comment]
Going to mark this as invalid. This is outside the scope of the current documentation.
