### ISSUE TITLE
Improvements to line referencing the "prior example"

### ISSUE THREAD

**Issue by fhightower** [ThreatConnect-Inc/ThreatConnect_Developer_Docs#31]
(Original issue 29)

There are lines that read:
"Note: In the prior example, no API calls are made until the commit() method is invoked."

throughout the docs.  I believe they should be changed to make it more clear what code snippet is being referenced, but I'll wait to see how the docs are formatted in the new system.

**Comment by slabe-svetlo** [comment]
I'l work on this. There's also a bunch of the chevrons which created the little notes in the code column that also need to be deleted.

**Comment by fhightower** [comment]
This has been fixed.
