### ISSUE TITLE
Associated groups snippet heading update

### ISSUE THREAD

**Issue by fhightower** [ThreatConnect-Inc/ThreatConnect_Developer_Docs#32]
(Original issue 30)

Change the line that reads:
"The following example demonstrates how to Associate a Group to an Adversary Resource. For other Resource Groups, Indicators, and Victims, the same method should be used:"

to read:
"The following example demonstrates how to Associate an Adversary Resource with an Incident and Signature Resource. For other Resource Groups, Indicators, and Victims, the same method should be used:"

**Comment by fhightower** [comment]
This issue can be found here:
http://docs.threatconnect.com/#associations185

**Comment by brikardtc** [comment]
Taking care of this one now.

**Comment by brikardtc** [comment]
Fixed in branch: associated_group_snippet
