### ISSUE TITLE
Fix incorrect code highlight: filter1.add_tag('EXAMPLE')

### ISSUE THREAD

**Issue by fhightower** [ThreatConnect-Inc/ThreatConnect_Developer_Docs#63]
### Description:
The code highlight reading: `filter1.add_tag('EXAMPLE')` is often incorrect as the corresponding line in the code snippet reads: `filter1.add_tag('APT')`.

### Link(s):
- http://docs.threatconnect.com/#groups-retrieve-filter-example

**Comment by brikardtc** [comment]
Fixed in branch: tag_filter_fix
