### ISSUE TITLE
Duplicate Headings

### ISSUE THREAD

**Issue by fhightower** [ThreatConnect-Inc/ThreatConnect_Developer_Docs#69]
### Description:
There are duplicate headings:

```
###Indicator Activity

###Indicator Activity
```

Not sure if the first one should be larger than the first or if the first one should be removed.

### Link(s):
- http://docs.threatconnect.com/#indicator-activity27

**Comment by brikardtc** [comment]
Fix in branch: Duplicate_Heading_Fix.
