### ISSUE TITLE
Fix owner names in URLs

### ISSUE THREAD

**Issue by fhightower** [ThreatConnect-Inc/ThreatConnect_Developer_Docs#70]
### Description:
There are many URLs that contain: `owner=Organization Name`, but they should be `owner=Organization%20Name`.

### Link(s):
- http://docs.threatconnect.com/#dns-resolutions-resource-type

**Comment by brikardtc** [comment]
Fixed in branch - Fix_owner_name

**Comment by fhightower** [comment]
Thanks @brikardtc . As long as you are comfortable that the changes you have made are correct, you don't have to create a branch for every issue. What ever is easiest for you.

**Comment by brikardtc** [comment]
@fhightower No problem. I'm following the same path as slabe-svetlo. Branch for each issue to keep it tidier. 👍
