### ISSUE TITLE
Redo the structure of the docs

### ISSUE THREAD

**Issue by fhightower** [ThreatConnect-Inc/ThreatConnect_Developer_Docs#77]
### Description:
The structure of the docs is very confusing right now and not very consistent. Consider splitting up the sections into different files. We at least need to design an outline for the docs which we follow.

**Comment by slabe-svetlo** [comment]
Yup, I agree. We're starting to go over it with more effort. Come up with some ideas for this Thursday and I'll have some as well.

**Comment by fhightower** [comment]
FYSA: I'm working on moving the docs over to restructured text behind the scenes which will allow us to more easily manage the structure of the docs.

**Comment by fhightower** [comment]
Done (at least with the Python Docs which were the highest priority)!
