### ISSUE TITLE
Fix headings in group associations section

### ISSUE THREAD

**Issue by fhightower** [ThreatConnect-Inc/ThreatConnect_Developer_Docs#80]
### Description:
The headings are of incorrect sizes below. Also, there is a repeated code snippet in this section with the code `for i_association in indicator.indicator_associations`. Not sure if this is intentional/useful or not.

### Link(s):
- http://docs.threatconnect.com/#group-associations

**Comment by brikardtc** [comment]
@fhightower not sure what you mean here - please see the attached for how this looks in the editor and preview.
![screen shot 2017-02-07 at 3 44 52 pm](https://cloud.githubusercontent.com/assets/25487200/22710709/66fc5e94-ed4c-11e6-974b-e0fcb2a7e2a3.png)

**Comment by fhightower** [comment]
Ah, yes. I wasn't very clear. As far as the headings of incorrect sizes, the "Group Associations" heading which is found at the link above is larger than the "Indicator Associations" and "Victim Associations" headings which are just below it in the documentation. I propose we wait on this fix issue until we rethink the structure of the docs as a whole and reorganize the hierarchy (see #77).

**Comment by brikardtc** [comment]
I agree with the assessment of waiting for #77

**Comment by fhightower** [comment]
Fixed with the hierarchy update.
