### ISSUE TITLE
Update the links in the TC repos. to point to the correct documentation

### ISSUE THREAD

**Issue by fhightower** [ThreatConnect-Inc/ThreatConnect_Developer_Docs#81]
### Link(s):
- https://github.com/ThreatConnect-Inc/threatconnect-javascript/blob/master/examples/README.md - (add a link to this one)
- https://github.com/ThreatConnect-Inc/threatconnect-java/blob/master/README.md

- [x] Java
- [x] Python
- [x] Js

**Comment by slabe-svetlo** [comment]
Working this one...

**Comment by slabe-svetlo** [comment]
I think I got this if they were in the README.md?

**Comment by fhightower** [comment]
Sorry, I was referring to the links in the readmes that are found in the other repos. For example, the Java SDK readme (https://github.com/ThreatConnect-Inc/threatconnect-java/blob/master/README.md) contains a link to a documentation site that no longer exists.

**Comment by fhightower** [comment]
There is already a PR in the Java SDK (https://github.com/ThreatConnect-Inc/threatconnect-java/pull/3) to fix the link in the Java readme.

**Comment by fhightower** [comment]
I've created PRs in all SDKs (and TCEX) to add the correct links.
