### ISSUE TITLE
Clean up Table 40

### ISSUE THREAD

**Issue by fhightower** [ThreatConnect-Inc/ThreatConnect_Developer_Docs#85]
### Description:
Table 40 needs to be cleaned up

### Link(s):
- The table in question is located just **above**: https://github.com/ThreatConnect-Inc/ThreatConnect_Developer_Docs/blob/master/api_docs.md#batch-indicator-input-file-format

**Comment by slabe-svetlo** [comment]
Yeah, the slashes are breaking it. I'll update this one.

**Comment by slabe-svetlo** [comment]
Completed.
