### ISSUE TITLE
Clarify the availability of JS spaces apps

### ISSUE THREAD

**Issue by fhightower** [ThreatConnect-Inc/ThreatConnect_Developer_Docs#87]
### Description:
Rephrase the following statement to make it more clear what is possible with a free account:
"JavaScript apps may be installed by any user with a [Basic account or higher ](https://www.threatconnect.com/platform/editions/#basic) with the [Spaces visualization feature](http://kb.threatconnect.com/customer/en/portal/articles/2256255-creating-a-space)"

The word "installed" is confusing as most users (except sys admins.) can't *install* apps, but can only *add* or *enable* them in their account.

**Comment by brikardtc** [comment]
This is mentioned within index.md and README.md files. Working on getting this updated.

**Comment by brikardtc** [comment]
Fixed in merge #100
