### ISSUE TITLE
Update dependancies and wording

### ISSUE THREAD

**Issue by slabe-svetlo** [ThreatConnect-Inc/ThreatConnect_Developer_Docs#89]
### Description:
We're listing some older version of the TC SDK, Python packages, etc. Suggest to reword to point to Maven/PyPi/GitHub repo and not list any version numbers to make maintenance easier in the long run

### Link(s):

- [x] https://github.com/ThreatConnect-Inc/threatconnect-python

- [x] https://github.com/ThreatConnect-Inc/threatconnect-javascript

**Comment by fhightower** [comment]
I agree this is a best practice. I'm going to close it out unless you have any other, specific things we should fix @slabe-svetlo .
